
package modules.views;

import javafx.geometry.Insets;
import javafx.scene.control.*;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import modules.controllers.AttachmentController;
import modules.models.Attachment;
import config.Database;

import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.UUID;

public class AttachmentForm extends GridPane {

    private TextField urlField;
    private TextArea descriptionField;

    private Connection conn;
    private BorderPane mainLayout;
    private UUID animalId;

    public AttachmentForm(BorderPane mainLayout, UUID animalId) {
        this.mainLayout = mainLayout;
        this.animalId = animalId;

        urlField = new TextField();
        descriptionField = new TextArea();

        try {
            this.conn = Database.getConnection();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        Button saveButton = new Button("Salvar");
        saveButton.setOnAction(e -> saveAttachment());

        Button backButton = new Button("Voltar");
        backButton.setOnAction(e -> mainLayout.setCenter(new AnimalListView(mainLayout)));

        HBox buttonBox = new HBox(10, saveButton, backButton);

        this.setVgap(10);
        this.setHgap(10);
        this.setPadding(new Insets(20, 20, 20, 20));

        int row = 0;
        this.add(new Label("URL:"), 0, row); this.add(urlField, 1, row++);
        this.add(new Label("Descrição:"), 0, row); this.add(descriptionField, 1, row++);
        this.add(buttonBox, 1, row);

        urlField.setPrefWidth(240);
        descriptionField.setPrefWidth(240);
        descriptionField.setPrefHeight(100);

        this.setPrefSize(520, 600);
    }

    private void saveAttachment() {
        String url = urlField.getText();
        String description = descriptionField.getText();
        if (description != null && description.trim().isEmpty()) {
            description = null;
        }

        Attachment a = new Attachment(
                null, // id is generated by the database
                url, 
                description, 
                this.animalId,
                LocalDateTime.now()
        );

        try {
            AttachmentController.addAttachment(conn, a);
            System.out.println("Anexo adicionado com sucesso!");
            mainLayout.setCenter(new AnimalListView(mainLayout));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
